=== TomMussard/XML/XML/TD1_XML/public_html/dressing.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT dressing (tshirts+,sweats+,pantalons+,chaussures+)>
<!ELEMENT tshirts (taille?,couleur?,quantite?)>
<!ELEMENT sweats (taille?,couleur?,quantite?)>
<!ELEMENT pantalons (taille?,couleur?,quantite?)>
<!ELEMENT chaussures (taille?,couleur?,quantite?)>
<!ELEMENT taille (#PCDATA)>
<!ELEMENT couleur (#PCDATA)>
<!ELEMENT quantite (#PCDATA)>

<!ATTLIST tshirts (taille | couleur | quantite) #REQUIRED>
<!ATTLIST sweats (taille | couleur | quantite) #REQUIRED>
<!ATTLIST pantalons (taille | couleur | quantite) #REQUIRED>
<!ATTLIST chaussures (taille | couleur | quantite) #REQUIRED>

=== TomMussard/XML/XML/TD1_XML/public_html/dressing.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dressing SYSTEM "dressing.dtd">
<?xml-stylesheet href="dressing.css" type="text/css" ?>


<dressing>
    <tshirts>
        <taille>M</taille>
            <couleur>rouge</couleur>
            <quantite>17</quantite>
    </tshirts>
    <sweats>
        <taille>M</taille>
            <couleur>noir</couleur>
            <quantite>9</quantite>
    </sweats>
    <pantalons>
        <taille>40</taille>
            <couleur>bleu</couleur>
            <quantite>6</quantite>
    </pantalons>
    <chaussures>
        <taille>43</taille>
            <couleur>jaune</couleur>
            <quantite>8</quantite>
    </chaussures>
</dressing>
