=== TomMussard/XML/XML/Exercicexml/public_html/iphone.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT iphone (identité+)>
<!ELEMENT identité (modele*,date*,couleur*)>
<!ELEMENT modele (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT couleur (#PCDATA)>

<!ATTLIST classe nom CDATA #IMPLIED>

=== TomMussard/XML/XML/Exercicexml/public_html/iphone.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lycee SYSTEM "iphone.dtd"
<iphone>
    <iphone nom="Iphone">
        <identite>
            <modele>Iphone 14</modele>
            <date>10/09/202</date>
            <couleur>Vert turquoise</couleur>
        </identite>
         <identite>
            <modele>Iphone 3GS</modele>
            <date>25/08/1997</date>
            <couleur>marron</couleur>
        </identite>
    </iphone>
